{% set name = "scipy-doctest" %}
{% set version = "1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scipy_doctest-{{ version }}.tar.gz
  sha256: 5d5e51a9e3b0849c74b3e3debc8018d9b44dee7be119cfd410d3a5986018a220

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19.5
    - pytest

test:
  imports:
    - scipy_doctest
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scipy/scipy_doctest
  summary: Configurable, whitespace-insensitive, floating-point-aware doctest helpers.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucascolley
